LOCAL_PATH := $(call my-dir)
_IMPORT_PREFIX := $(LOCAL_PATH)/../../..

include $(CLEAR_VARS)
LOCAL_MODULE := SDL2test
LOCAL_SRC_FILES := $(_IMPORT_PREFIX)//home/zackmon/.ndk-pkg/installed/android-21-x86_64/4dc19fcc84173fe86adf54619d529445d8fe1c932ec387561183e9e792df76c2/lib/libSDL2_test.a
LOCAL_CPP_FEATURES := rtti exceptions
# COMPATIBLE_INTERFACE_STRING SDL_VERSION
LOCAL_EXPORT_C_INCLUDES := ${_IMPORT_PREFIX}/include\
${_IMPORT_PREFIX}/include/SDL2
# INTERFACE_SDL_VERSION SDL2
include $(PREBUILT_STATIC_LIBRARY)

