ffmpeg -> libmp3lame
ffmpeg -> libtheora
ffmpeg -> libvorbis
ffmpeg -> libspeex
ffmpeg -> librav1e
ffmpeg -> libdav1d
ffmpeg -> libx264
ffmpeg -> libx265
ffmpeg -> libopus
ffmpeg -> libxvid
ffmpeg -> libvpx
ffmpeg -> libwebp
ffmpeg -> libtiff
ffmpeg -> libpng
ffmpeg -> libjpeg-turbo
ffmpeg -> libgif
ffmpeg -> libxml2
ffmpeg -> sdl2
libxml2 -> libiconv
libxml2 -> libz
libpng -> libz
libtiff -> libzstd
libtiff -> liblzma
libtiff -> libz
libspeex -> libogg
libspeex -> libspeexdsp
libvorbis -> libogg
libtheora -> libogg
