     CC_FOR_BUILD='/usr/bin/cc'
   OBJC_FOR_BUILD='/usr/bin/cc'
    CXX_FOR_BUILD='/usr/bin/c++'
     AS_FOR_BUILD='/usr/bin/as'
     AR_FOR_BUILD='/usr/bin/ar'
 RANLIB_FOR_BUILD='/usr/bin/ranlib'
     LD_FOR_BUILD='/usr/bin/ld'
     NM_FOR_BUILD='/usr/bin/nm'
   SIZE_FOR_BUILD='/usr/bin/size'
  STRIP_FOR_BUILD='/usr/bin/strip'
STRINGS_FOR_BUILD='/usr/bin/strings'
OBJDUMP_FOR_BUILD='/usr/bin/objdump'
OBJCOPY_FOR_BUILD='/usr/bin/objcopy'
READELF_FOR_BUILD='/usr/bin/readelf'
SYSROOT_FOR_BUILD=''

CCFLAGS_FOR_BUILD='-fPIC -fno-common -Os'
LDFLAGS_FOR_BUILD='-Wl,--as-needed -Wl,-z,muldefs -Wl,--allow-multiple-definition -Wl,-S'
