LOCAL_PATH := $(call my-dir)
_IMPORT_PREFIX := $(LOCAL_PATH)/../../..

include $(CLEAR_VARS)
LOCAL_MODULE := SDL2test
LOCAL_SRC_FILES := $(_IMPORT_PREFIX)//home/zackmon/.ndk-pkg/installed/android-21-armeabi-v7a/715dc19998c8dc8dce679b0c17f541efd621214638246c031a760bccd6e97a2a/lib/libSDL2_test.a
LOCAL_CPP_FEATURES := rtti exceptions
# COMPATIBLE_INTERFACE_STRING SDL_VERSION
LOCAL_EXPORT_C_INCLUDES := ${_IMPORT_PREFIX}/include\
${_IMPORT_PREFIX}/include/SDL2
# INTERFACE_SDL_VERSION SDL2
include $(PREBUILT_STATIC_LIBRARY)

